version: '3.6'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${THEME_NAME}_wp
      MYSQL_USER: ${THEME_NAME}
      MYSQL_PASSWORD: ${THEME_NAME}
    networks:
      - wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
    - ./wp-content:/var/www/html/wp-content/
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300M
    networks:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
  
    restart: always
    volumes:
      - ./project-assets/${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./project-assets/plugins:/var/www/html/wp-content/plugins
      - ./project-assets/uploads:/var/www/html/wp-content/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${THEME_NAME}
      WORDPRESS_DB_PASSWORD: ${THEME_NAME}
      WORDPRESS_DB_NAME: ${THEME_NAME}_wp
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_DISPLAY', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG', true);
        define('FS_METHOD', 'direct');
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_HOME','http://localhost:8000');
        define('WP_SITEURL','http://localhost:8000');
    ports:
      - 8000:80
    networks:
      - wordpress

networks:
  wordpress:
    name: ${THEME_NAME}

volumes:
  db_data:
